language: node_js
node_js:
  - 10.11.0

cache: yarn

env:
  global:
    - NODE_ENV=$APP_ENV

dist: trusty

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
  - npm ci

script:
  - yarn test:prod
  - yarn build:prod

before_deploy:
  - cd dist/

deploy:
  skip_cleanup: true
  keep-history: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    repo: octaform/octaform
