language: node_js
node_js:
  - 10.11.0

cache: npm

env:
  global:
    - NODE_ENV=$APP_ENV
  
before_script:
  - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
  - npm install

script:
  - npm run test:prod
  - npm run build:prod

before_deploy:
  - cd dist/

deploy:
  skip_cleanup: true
  keep-history: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    repo: octaform/octaform
