version: 2

defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:10.11.0

  environment:
    NODE_ENV: ${APP_ENV}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Restore local dependencies from cache
      - restore_cache:
          keys: 
            - v1-dependency-cache-{{ checksum "package.json" }}
            - v1-dependency-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test the source code
      - run:
          name: Testing
          command: npm run test:prod

      # Test the source code
      - run:
          name: Building
          command: npm run build:prod

      - persist_to_workspace:
          root: ~/tmp
          paths: .

  store_artifactory:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp

      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh

      - run: mkdir ./artifactory
      - run: zip -r artifactory/dist-$CIRCLE_BUILD_NUM.zip dist/

      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
      - run: ./jfrog rt u ./artifactory/dist-*.zip $ARTIFACTORY_REPO --build-name=octaform-artifact --build-number=$CIRCLE_BUILD_NUM
      - run: ./jfrog rt bce octaform-artifact $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
      - run: ./jfrog rt bp octaform-artifact $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc

      - run:
          name: Publishing to NPM
          command: npm publish dist/

workflows:
  version: 2
  # Build and test
  build_and_publish:
    jobs:
      # Build application
      - build:
          filters:
            branches:
              only: master
      - store_artifactory:
          requires:
            - build
          filters:
            branches:
              only: master

      # Publish to NPM
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
